### ISSUE TITLE
Enchant Chest - Glorious Stats

### ISSUE THREAD

**Issue by PrideQualityAssurance** [RealLushen/Aternion20#1]
**Wowhead.com (and Tauri database link included, since it's MoP) link:**
 https://www.wowhead.com/item=74708/enchant-chest-glorious-stats
https://mop-shoot.tauri.hu/?item=74708

**Description of the bug:**
Says the spell is unavailable to me when trying to enchant my chest piece with it.
Easy fix would be to remove it from the vendor, since the vendor already have a stat enchant for chest that actually works (https://www.wowhead.com/item=52779/enchant-chest-peerless-stats).

**Expected Behavior:**
It should enchant my chest piece.

**Steps to Reproduce (if needed):**
.add 74708
Try to enchant a chest piece.

**Screenshots/video (if needed):**
https://i.imgur.com/DawhXJV.png

**Comment by RealLushen** [comment]
Hello PrideQualityAssurance,
thanks for your detailed Bug report, we removed the Enchant from the Vendor!

Wish you a great stay here at Aternion20!
~ Lushen
